name: ci

on:
  push:
    branches: 
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: build, test and release
      run: |
        set -e
        npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        npm install
        npm run build
        npm run test
        npm publish --access public --no-git-checks
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
